In [16]:
transactions=[
    {"Bread","Butter","Milk"},
     {"Bread","Milk"},
    {"Butter","Milk"},
    {"Bread","Butter"}
   ]

tid={}
for i,t in enumerate(transactions):
    for item in t:
        if item not in tid:
            tid[item]=set()
        tid[item].add(i)

print("TID Lists:",tid)

bread_butter = tid["Bread"]&tid["Butter"]
bread_milk=tid["Bread"]&tid["Milk"]
butter_milk=tid["Butter"]&tid["Milk"]

print("Support of Bread and Butter",len(bread_butter))
print("Support of Bread and Milk",len(bread_milk))
print("Support of Butter and Milk",len(butter_milk))

min_sup=2
if(len(bread_butter)==min_sup):
    print("Bread and Butter is frequent")
if(len(bread_milk)==min_sup):
    print("Bread and Milk is frequent")
if(len(butter_milk)==min_sup):
    print("Butter and Milk is frequent")

TID Lists: {'Milk': {0, 1, 2}, 'Bread': {0, 1, 3}, 'Butter': {0, 2, 3}}
Support of Bread and Butter 2
Support of Bread and Milk 2
Support of Butter and Milk 2
Bread and Butter is frequent
Bread and Milk is frequent
Butter and Milk is frequent


In [21]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score

X,Y = make_classification(n_samples=600,n_features=6,random_state=42)
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=42)

bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=30,
    bootstrap=True,
    random_state=42
)
bag.fit(x_train,y_train)
print("Accuracy score:",accuracy_score(y_test,bag.predict(x_test)))

Accuracy score: 0.9333333333333333


In [26]:
import numpy as np
from sklearn.decomposition import FastICA
S = np.array([[2,1],[3,-2],[4,1],[5,-2]])
A = np.array([[2,1],[1,3]])

mix = S@A.T
print("Mixed signals:\n",mix)

ica = FastICA(n_components=2,random_state=42)
U = ica.fit_transform(mix)

print("Original Source:\n",S)
print("Recovered Source:\n",U)

Mixed signals:
 [[ 5  5]
 [ 4 -3]
 [ 9  7]
 [ 8 -1]]
Original Source:
 [[ 2  1]
 [ 3 -2]
 [ 4  1]
 [ 5 -2]]
Recovered Source:
 [[ 0.99999971 -1.00000029]
 [-1.00000029 -0.99999971]
 [ 1.00000029  0.99999971]
 [-0.99999971  1.00000029]]


In [27]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error

X,Y = make_regression(n_samples=250,n_features=6,noise=10,random_state=42)

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

model = ElasticNet(alpha=0.8,l1_ratio=0.7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("MSE:",mean_squared_error(y_test,y_pred))

MSE: 686.2758473698825
